# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dashboard_api import DashboardApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self):
        self.api = DashboardApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dashboard_get_backup_repositories_report(self):
        """Test case for dashboard_get_backup_repositories_report

        Get Collection of Available Backup Repositories  # noqa: E501
        """
        pass

    def test_dashboard_get_protected_vms(self):
        """Test case for dashboard_get_protected_vms

        Get Number of Protected VMs  # noqa: E501
        """
        pass

    def test_dashboard_get_protected_vms_in_cluster(self):
        """Test case for dashboard_get_protected_vms_in_cluster

        Get Collection of Protected VMs  # noqa: E501
        """
        pass

    def test_dashboard_get_session_ratio_report(self):
        """Test case for dashboard_get_session_ratio_report

        Get Job Type Statistics  # noqa: E501
        """
        pass

    def test_dashboard_get_sessions_summary_report(self):
        """Test case for dashboard_get_sessions_summary_report

        Get Session Status Statistics for Last 24 Hours  # noqa: E501
        """
        pass

    def test_dashboard_get_system_monitoring_info(self):
        """Test case for dashboard_get_system_monitoring_info

        Get Resource Usage Statistics  # noqa: E501
        """
        pass

    def test_dashboard_get_top_jobs_duration_report(self):
        """Test case for dashboard_get_top_jobs_duration_report

        Get Collection of Recent Job Sessions Duration  # noqa: E501
        """
        pass

    def test_dashboard_get_unprotected_vms_in_cluster(self):
        """Test case for dashboard_get_unprotected_vms_in_cluster

        Get Collection of Unprotected VMs  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
