# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.clusters_api import ClustersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClustersApi(unittest.TestCase):
    """ClustersApi unit test stubs"""

    def setUp(self):
        self.api = ClustersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_clusters_get(self):
        """Test case for clusters_get

        Get Collection of Nutanix AHV Clusters  # noqa: E501
        """
        pass

    def test_clusters_get_auto_protection(self):
        """Test case for clusters_get_auto_protection

        Get Cluster Auto-Protection Settings  # noqa: E501
        """
        pass

    def test_clusters_get_by_id(self):
        """Test case for clusters_get_by_id

        Get Nutanix AHV Cluster Data  # noqa: E501
        """
        pass

    def test_clusters_get_networks(self):
        """Test case for clusters_get_networks

        Get Collection of Networks  # noqa: E501
        """
        pass

    def test_clusters_get_pds(self):
        """Test case for clusters_get_pds

        Get Collection of Protection Domains  # noqa: E501
        """
        pass

    def test_clusters_get_storage_containers(self):
        """Test case for clusters_get_storage_containers

        Get Collection of Storage Containers  # noqa: E501
        """
        pass

    def test_clusters_get_vm_by_id(self):
        """Test case for clusters_get_vm_by_id

        Get Virtual Machine Data  # noqa: E501
        """
        pass

    def test_clusters_get_vms(self):
        """Test case for clusters_get_vms

        Get Collection of Virtual Machines  # noqa: E501
        """
        pass

    def test_clusters_get_volume_group_by_id(self):
        """Test case for clusters_get_volume_group_by_id

        Get Volume Group Data  # noqa: E501
        """
        pass

    def test_clusters_get_volume_groups(self):
        """Test case for clusters_get_volume_groups

        Get Collection of Volume Groups in Cluster  # noqa: E501
        """
        pass

    def test_clusters_refresh_pds_async(self):
        """Test case for clusters_refresh_pds_async

        Infrastructure Rescan for Protection Domains  # noqa: E501
        """
        pass

    def test_clusters_refresh_vms_async(self):
        """Test case for clusters_refresh_vms_async

        Infrastructure Rescan for Virtual Machines  # noqa: E501
        """
        pass

    def test_clusters_refresh_volume_groups(self):
        """Test case for clusters_refresh_volume_groups

        Infrastructure Rescan for Volume Groups  # noqa: E501
        """
        pass

    def test_clusters_rescan_snapshots(self):
        """Test case for clusters_rescan_snapshots

        Cluster Rescan for Snapshots  # noqa: E501
        """
        pass

    def test_clusters_update_auto_protection_settings(self):
        """Test case for clusters_update_auto_protection_settings

        Modify Cluster Auto-Protection Settings  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
