# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.restore_points_api import RestorePointsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRestorePointsApi(unittest.TestCase):
    """RestorePointsApi unit test stubs"""

    def setUp(self):
        self.api = RestorePointsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_restore_points_delete_by_id(self):
        """Test case for restore_points_delete_by_id

        Delete Restore Point  # noqa: E501
        """
        pass

    def test_restore_points_disk_restore(self):
        """Test case for restore_points_disk_restore

        Perform Disk Restore  # noqa: E501
        """
        pass

    def test_restore_points_get(self):
        """Test case for restore_points_get

        Get VM Restore Points  # noqa: E501
        """
        pass

    def test_restore_points_get_backup_by_id(self):
        """Test case for restore_points_get_backup_by_id

        Get Backup Data  # noqa: E501
        """
        pass

    def test_restore_points_get_backup_snapshot_by_id(self):
        """Test case for restore_points_get_backup_snapshot_by_id

        Get Backup Snapshot Data  # noqa: E501
        """
        pass

    def test_restore_points_get_disks_from_restore_point(self):
        """Test case for restore_points_get_disks_from_restore_point

        Get Collection of Disks From Restore Point  # noqa: E501
        """
        pass

    def test_restore_points_get_network_adapters_from_restore_point(self):
        """Test case for restore_points_get_network_adapters_from_restore_point

        Get Collection of Network Adapters From Restore Point  # noqa: E501
        """
        pass

    def test_restore_points_get_protection_domain_snapshot_by_id(self):
        """Test case for restore_points_get_protection_domain_snapshot_by_id

        Get Protection Domain Snapshot Data  # noqa: E501
        """
        pass

    def test_restore_points_get_restore_point_by_id(self):
        """Test case for restore_points_get_restore_point_by_id

        Get Restore Point Data  # noqa: E501
        """
        pass

    def test_restore_points_get_user_snapshot_by_id(self):
        """Test case for restore_points_get_user_snapshot_by_id

        Get User Snapshot Data  # noqa: E501
        """
        pass

    def test_restore_points_restore(self):
        """Test case for restore_points_restore

        Perform VM Restore  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
