# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ArchiveLogsParameters(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'from_utc': 'datetime',
        'to_utc': 'datetime'
    }

    attribute_map = {
        'from_utc': 'fromUtc',
        'to_utc': 'toUtc'
    }

    def __init__(self, from_utc=None, to_utc=None):  # noqa: E501
        """ArchiveLogsParameters - a model defined in Swagger"""  # noqa: E501
        self._from_utc = None
        self._to_utc = None
        self.discriminator = None
        if from_utc is not None:
            self.from_utc = from_utc
        if to_utc is not None:
            self.to_utc = to_utc

    @property
    def from_utc(self):
        """Gets the from_utc of this ArchiveLogsParameters.  # noqa: E501


        :return: The from_utc of this ArchiveLogsParameters.  # noqa: E501
        :rtype: datetime
        """
        return self._from_utc

    @from_utc.setter
    def from_utc(self, from_utc):
        """Sets the from_utc of this ArchiveLogsParameters.


        :param from_utc: The from_utc of this ArchiveLogsParameters.  # noqa: E501
        :type: datetime
        """

        self._from_utc = from_utc

    @property
    def to_utc(self):
        """Gets the to_utc of this ArchiveLogsParameters.  # noqa: E501


        :return: The to_utc of this ArchiveLogsParameters.  # noqa: E501
        :rtype: datetime
        """
        return self._to_utc

    @to_utc.setter
    def to_utc(self, to_utc):
        """Sets the to_utc of this ArchiveLogsParameters.


        :param to_utc: The to_utc of this ArchiveLogsParameters.  # noqa: E501
        :type: datetime
        """

        self._to_utc = to_utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ArchiveLogsParameters, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ArchiveLogsParameters):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
