# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DiskInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bus_type': 'AhvBusType',
        'index': 'int'
    }

    attribute_map = {
        'bus_type': 'busType',
        'index': 'index'
    }

    def __init__(self, bus_type=None, index=None):  # noqa: E501
        """DiskInfo - a model defined in Swagger"""  # noqa: E501
        self._bus_type = None
        self._index = None
        self.discriminator = None
        self.bus_type = bus_type
        self.index = index

    @property
    def bus_type(self):
        """Gets the bus_type of this DiskInfo.  # noqa: E501


        :return: The bus_type of this DiskInfo.  # noqa: E501
        :rtype: AhvBusType
        """
        return self._bus_type

    @bus_type.setter
    def bus_type(self, bus_type):
        """Sets the bus_type of this DiskInfo.


        :param bus_type: The bus_type of this DiskInfo.  # noqa: E501
        :type: AhvBusType
        """
        if bus_type is None:
            raise ValueError("Invalid value for `bus_type`, must not be `None`")  # noqa: E501

        self._bus_type = bus_type

    @property
    def index(self):
        """Gets the index of this DiskInfo.  # noqa: E501


        :return: The index of this DiskInfo.  # noqa: E501
        :rtype: int
        """
        return self._index

    @index.setter
    def index(self, index):
        """Sets the index of this DiskInfo.


        :param index: The index of this DiskInfo.  # noqa: E501
        :type: int
        """
        if index is None:
            raise ValueError("Invalid value for `index`, must not be `None`")  # noqa: E501

        self._index = index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DiskInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DiskInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
