# coding: utf-8

"""
    Veeam Backup for Nutanix AHV REST API 4.0

    This REST API reference lists types of Veeam Backup for Nutanix AHV entities,  and contains description of collections and resources which stand for these entities.  Every resource has a JSON object model and includes application data and REST API metadata.  Application data is represented by properties associated with Veeam Backup for Nutanix AHV entities.  REST API metadata is represented by properties specific to the REST API, such as resource IDs, URLs and relationships.  The reference also includes methods that represent operations available to a resource or collection.   # noqa: E501

    OpenAPI spec version: V4
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MemoryUsageInfo(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'time_utc': 'datetime',
        'used_percent': 'int'
    }

    attribute_map = {
        'time_utc': 'timeUtc',
        'used_percent': 'usedPercent'
    }

    def __init__(self, time_utc=None, used_percent=None):  # noqa: E501
        """MemoryUsageInfo - a model defined in Swagger"""  # noqa: E501
        self._time_utc = None
        self._used_percent = None
        self.discriminator = None
        if time_utc is not None:
            self.time_utc = time_utc
        if used_percent is not None:
            self.used_percent = used_percent

    @property
    def time_utc(self):
        """Gets the time_utc of this MemoryUsageInfo.  # noqa: E501

        Date and time of a RAM consumption record.  # noqa: E501

        :return: The time_utc of this MemoryUsageInfo.  # noqa: E501
        :rtype: datetime
        """
        return self._time_utc

    @time_utc.setter
    def time_utc(self, time_utc):
        """Sets the time_utc of this MemoryUsageInfo.

        Date and time of a RAM consumption record.  # noqa: E501

        :param time_utc: The time_utc of this MemoryUsageInfo.  # noqa: E501
        :type: datetime
        """

        self._time_utc = time_utc

    @property
    def used_percent(self):
        """Gets the used_percent of this MemoryUsageInfo.  # noqa: E501

        RAM consumption (in percent).  # noqa: E501

        :return: The used_percent of this MemoryUsageInfo.  # noqa: E501
        :rtype: int
        """
        return self._used_percent

    @used_percent.setter
    def used_percent(self, used_percent):
        """Sets the used_percent of this MemoryUsageInfo.

        RAM consumption (in percent).  # noqa: E501

        :param used_percent: The used_percent of this MemoryUsageInfo.  # noqa: E501
        :type: int
        """

        self._used_percent = used_percent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MemoryUsageInfo, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MemoryUsageInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
